site_name: Protocol-denken
docs_dir: docs
site_dir: site
site_url: https://kadaster-labs.github.io/protocol-denken/
repo_url: https://github.com/kadaster-labs/protocol-denken
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    primary: custom
  language: nl
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant  
    - navigation.top
    - navigation.tracking
    - toc.follow
  icon:
    logo: material/play-network
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
